// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"11155111": {
		policy: "0x389ADa033D00dA6b59d9aF6aBe2b2DBcDD0DDBb3",
		policyData: "0xFEA8a5bC90c01ca26C9b49B9288774eBbd4b06a6",
		wasmCid: "bafybeief35ucfgdhqek62hsrvc2ndms3qrbguuntbxs2hg4ialgu5ly7va",
		policyCodeHash: "0xc40c81729d42f6c642532f354aeddcb7ca950905c3a213d0449f7cf5063bc273",
		deployedAt: "2026-06-12",
		notes: "round 2: tightened blockaid/guardrail/webacy allow rules; source-of-truth dist sync",
	},
} as const satisfies Readonly<Partial<Record<ChainId, Deployment>>>;
