// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "blockaid" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Gates vault deposits at transaction-submission time using Blockaid's EVM transaction scan (validation + simulation) to catch malicious calldata, frontend-redirect attacks, and value-skim simulations" as const;
export const PACK_LINK = "https://www.blockaid.io" as const;
export const PACK_AUTHOR = "" as const;
