// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: blockaid/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		deny_features: z
			.array(z.string())
			.describe(
				"Blockaid feature ids that, if present on a Warning-classified transaction, deny the deposit (e.g. ['unbounded_approval','honeypot','phishing'])",
			),
		max_outbound_inbound_ratio: z
			.number()
			.describe(
				"Maximum allowed simulated outbound-to-inbound USD value ratio. Above this, the transaction is treated as a value-skim and denied.",
			),
		require_received_shares: z
			.boolean()
			.describe(
				"Deny if the simulated state-diff shows the depositor receives no inbound asset (vault shares). Catches contracts that take funds without minting receipts.",
			),
	})
	.describe("Thresholds for the Blockaid transaction-time exploit gate")
	.strict();

export type Params = z.infer<typeof ParamsSchema>;
