// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: blockaid/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		chain: z.string().describe("Blockaid chain identifier (e.g. 'ethereum', 'base', 'arbitrum')."),
		from: z.string().describe("Sender / account address (0x-prefixed 20-byte address)."),
		to: z.string().describe("Recipient or contract address being called (0x-prefixed)."),
		value: z
			.string()
			.describe(
				"Transaction value in wei as a 0x-prefixed hex string. Defaults to '0x0' when omitted.",
			)
			.optional(),
		data: z
			.string()
			.describe("Transaction calldata as a 0x-prefixed hex string. Defaults to '0x' when omitted.")
			.optional(),
	})
	.describe("Inputs passed to the Blockaid policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
