// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "webacy" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Gates vault deposits based on Webacy's per-address risk score (DD Score), sanctions hits, and exploit-exposure flags" as const;
export const PACK_LINK = "https://webacy.com" as const;
export const PACK_AUTHOR = "" as const;
