// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: webacy/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		deny_on_sanctioned: z
			.boolean()
			.describe(
				"Deny when the address bucket is 'sanctioned' (any sanctions / OFAC / blocklist hit in the issues array)",
			),
		deny_on_high_risk: z
			.boolean()
			.describe("Deny when the address bucket is 'high' (DD score above 50)"),
		exploit_exposure_hits_max: z
			.number()
			.describe(
				"Maximum number of exploit / hack / drainer / stolen-funds tags allowed before denying. Setting to 1 means a single hit denies.",
			),
		medium_risk_max_deposit_usd: z
			.number()
			.describe(
				"Maximum allowed deposit (in USD) for medium-risk addresses. Above this, deposit is denied.",
			),
	})
	.describe("Thresholds for the Webacy depositor-reputation gate");

export type Params = z.infer<typeof ParamsSchema>;
