// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: webacy/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		address: z
			.string()
			.describe("Wallet or contract address (0x-prefixed) to score with the Webacy risk API."),
		chain: z
			.string()
			.describe(
				"Optional Webacy chain identifier (e.g. 'eth', 'bsc', 'polygon'). Defaults to the API's default chain when omitted.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Webacy address-risk policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
