// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"11155111": {
		policy: "0x091133448400b2Eb7Ee9DFfB294aDcC96975E617",
		policyData: "0x01B43c7D916f1FcCCBDdA185497e5A2DB7a326fA",
		wasmCid: "bafybeihabqf5jabjk2uc3aecf5tcy25fiu3cegs5czqz7v3nlydfmpry6m",
		policyCodeHash: "0x068304bb6d397b943002f4f7357b35778bba43eb30b85ec2d500c17d18c3e312",
		deployedAt: "2026-06-09",
		notes: "host-secrets fix; current",
	},
} as const satisfies Readonly<Partial<Record<ChainId, Deployment>>>;
