// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"11155111": {
		policy: "0xA1DE5A07dAb34Bd545C58b6e18A9009A8428e658",
		policyData: "0x571f1bAfAb0c47Ae0920c60d8C0a93871abc82cF",
		wasmCid: "bafybeigb2te7yt7xyc34h75zndnftu6g36gaegt6evkg2ebxfefotafy6e",
		policyCodeHash: "0xcd67effeb86e90807614caae91e99863ce47ab07d4e2b7219fdcccdcc0493e8a",
		deployedAt: "2026-06-14",
		notes: "Phase 0 Stream D — composite namespacing redeploy",
	},
} as const satisfies Readonly<Partial<Record<ChainId, Deployment>>>;
