// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: chainalysis/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		deny_on_sanctioned: z
			.boolean()
			.describe(
				"Deny when the public Sanctions Screening API returns any identification for the address",
			),
		deny_on_high_risk_category: z
			.boolean()
			.describe(
				"Deny when the Address Screening v2 risk enum is 'high' or 'severe' (requires CHAINALYSIS_SCREENING_KEY)",
			),
		risk_categories_blocklist: z
			.array(z.string())
			.describe(
				"Lowercased category strings that, if any are present in the screening response, deny the deposit (e.g. ['mixer','stolen_funds','ransomware'])",
			),
	})
	.describe("Thresholds for the Chainalysis sanctions / address-screening gate")
	.strict();

export type Params = z.infer<typeof ParamsSchema>;
