// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: chainalysis/secrets_schema.json
import { z } from "zod";

export const SecretsSchema = z
	.object({
		CHAINALYSIS_SANCTIONS_KEY: z.string().min(1),
		CHAINALYSIS_SCREENING_KEY: z.string().min(1).optional(),
	})
	.strict();

export type Secrets = z.infer<typeof SecretsSchema>;
