// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: chainalysis/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		address: z
			.string()
			.describe(
				"Wallet address (0x-prefixed) to screen against the Chainalysis sanctions and screening APIs.",
			),
	})
	.describe("Inputs passed to the Chainalysis policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
