// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "pharos_redemption" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Redemption-backed asset gate: admits a stablecoin only when direct redemption is available through an approved provider and mechanism, applicable limits support the intended position size, and the oracle response is current" as const;
export const PACK_LINK = "https://pharos.watch" as const;
export const PACK_AUTHOR = "Pharos" as const;
