// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: pharos_redemption/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		require_redemption_available: z
			.boolean()
			.describe("When true, an asset with no redemption route reported by Pharos denies outright."),
		approved_route_families: z
			.array(z.string())
			.describe(
				"Pharos redemption route families the curator will accept. Observed values include 'offchain-issuer'.",
			),
		approved_access_models: z
			.array(z.string())
			.describe(
				"Pharos redemption access models the curator will accept. Observed values include 'issuer-api'. Governs who may redeem.",
			),
		approved_settlement_models: z
			.array(z.string())
			.describe(
				"Pharos settlement models the curator will accept. Observed values include 'same-day'.",
			),
		required_route_status: z
			.string()
			.describe(
				"The route status the asset must report to be admissible. Pharos reports 'open' for a working route - NOT 'active'.",
			),
		min_route_score: z
			.number()
			.gte(0)
			.lte(100)
			.describe(
				"Minimum Pharos redemption route score (0-100), the composite quality measure across access, settlement, capacity, cost and execution certainty. Pharos exposes no 0-1 confidence value; capacity_confidence is a qualitative band, not a number.",
			),
		approved_capacity_confidence: z
			.array(z.string())
			.describe(
				"Acceptable qualitative capacity-confidence bands. Observed values include 'documented-bound'. Empty array disables this check.",
			),
		min_capacity_multiple: z
			.number()
			.gte(0)
			.describe(
				"Minimum ratio of the route's IMMEDIATE redemption capacity to the intended position. Pharos publishes an immediate capacity bound rather than a daily limit, so this sizes the position against what can be redeemed right now.",
			),
		max_reserve_elevated_risk_pct: z
			.number()
			.gte(0)
			.lte(100)
			.describe(
				"Maximum share (0-100) of reserves sitting in slices Pharos rates worse than low risk. Null reserve data fails soft.",
			),
		max_data_age_seconds: z
			.number()
			.gte(0)
			.describe(
				"Maximum tolerated age of the Pharos observation. The redemption-backstops feed refreshes on the order of hours, so values below ~4h will deny routinely. A null age fails soft here; list data_age_seconds in deny_on_missing_fields to catch it instead.",
			),
		deny_on_missing_fields: z
			.array(
				z.enum([
					"route_family",
					"access_model",
					"settlement_model",
					"route_status",
					"capacity_multiple",
					"route_score",
					"capacity_confidence",
					"reserve_elevated_risk_pct",
					"data_age_seconds",
				]),
			)
			.describe(
				"Field names the oracle must actually report. A null on a listed field denies as missing_<field>; unlisted fields fail soft. An empty list opts out entirely. NOTE: Pharos omits capacity_multiple whenever the caller passes no position size, so leave it unlisted unless every call supplies one.",
			),
	})
	.strict()
	.describe("Thresholds for the Pharos redemption-backed asset gate")
	.strict();

export type Params = z.infer<typeof ParamsSchema>;

export const ParamsJsonSchema = {
	type: "object",
	description: "Thresholds for the Pharos redemption-backed asset gate",
	properties: {
		require_redemption_available: {
			type: "boolean",
			description:
				"When true, an asset with no redemption route reported by Pharos denies outright.",
		},
		approved_route_families: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Pharos redemption route families the curator will accept. Observed values include 'offchain-issuer'.",
		},
		approved_access_models: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Pharos redemption access models the curator will accept. Observed values include 'issuer-api'. Governs who may redeem.",
		},
		approved_settlement_models: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Pharos settlement models the curator will accept. Observed values include 'same-day'.",
		},
		required_route_status: {
			type: "string",
			description:
				"The route status the asset must report to be admissible. Pharos reports 'open' for a working route - NOT 'active'.",
		},
		min_route_score: {
			type: "number",
			minimum: 0,
			maximum: 100,
			description:
				"Minimum Pharos redemption route score (0-100), the composite quality measure across access, settlement, capacity, cost and execution certainty. Pharos exposes no 0-1 confidence value; capacity_confidence is a qualitative band, not a number.",
		},
		approved_capacity_confidence: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Acceptable qualitative capacity-confidence bands. Observed values include 'documented-bound'. Empty array disables this check.",
		},
		min_capacity_multiple: {
			type: "number",
			minimum: 0,
			description:
				"Minimum ratio of the route's IMMEDIATE redemption capacity to the intended position. Pharos publishes an immediate capacity bound rather than a daily limit, so this sizes the position against what can be redeemed right now.",
		},
		max_reserve_elevated_risk_pct: {
			type: "number",
			minimum: 0,
			maximum: 100,
			description:
				"Maximum share (0-100) of reserves sitting in slices Pharos rates worse than low risk. Null reserve data fails soft.",
		},
		max_data_age_seconds: {
			type: "number",
			minimum: 0,
			description:
				"Maximum tolerated age of the Pharos observation. The redemption-backstops feed refreshes on the order of hours, so values below ~4h will deny routinely. A null age fails soft here; list data_age_seconds in deny_on_missing_fields to catch it instead.",
		},
		deny_on_missing_fields: {
			type: "array",
			items: {
				type: "string",
				enum: [
					"route_family",
					"access_model",
					"settlement_model",
					"route_status",
					"capacity_multiple",
					"route_score",
					"capacity_confidence",
					"reserve_elevated_risk_pct",
					"data_age_seconds",
				],
			},
			description:
				"Field names the oracle must actually report. A null on a listed field denies as missing_<field>; unlisted fields fail soft. An empty list opts out entirely. NOTE: Pharos omits capacity_multiple whenever the caller passes no position size, so leave it unlisted unless every call supplies one.",
		},
	},
	required: [
		"require_redemption_available",
		"approved_route_families",
		"approved_access_models",
		"approved_settlement_models",
		"required_route_status",
		"min_route_score",
		"approved_capacity_confidence",
		"min_capacity_multiple",
		"max_reserve_elevated_risk_pct",
		"max_data_age_seconds",
		"deny_on_missing_fields",
	],
	additionalProperties: false,
} as const;
