// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: pharos_redemption/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		stablecoin_id: z
			.string()
			.describe(
				"Canonical Pharos stablecoin identifier in ticker-issuer form, e.g. 'usdc-circle'.",
			),
		transaction_amount_usd: z
			.number()
			.gte(0)
			.describe(
				"USD notional of the intended position, checked against the redemption minimum and daily limit. CALLER-SUPPLIED and therefore NOT attested - see this pack's README. Defaults to 0 when omitted, which leaves the limit ratio undefined and fail-soft.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Pharos redemption-backed asset policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
