// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "xerberus_liquidity_exit" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Liquidity exit gate: denies acquiring a position that cannot be unwound within a curator-set number of days at a bounded market impact, or when the Xerberus data is stale" as const;
export const PACK_LINK = "https://xerberus.io" as const;
export const PACK_AUTHOR = "Xerberus" as const;
