// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: xerberus_liquidity_exit/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		token: z
			.string()
			.describe(
				"Token contract address (0x-prefixed) of the asset being acquired. Symbols are accepted by Xerberus but are ambiguous and cannot be bound to the intent; use the address in production.",
			),
		usd_notional: z.number().gte(0).describe("Proposed position size in USD."),
		impact_pct: z
			.number()
			.gte(0)
			.lte(100)
			.describe(
				"Optional maximum acceptable market impact in percent. Xerberus defaults apply when omitted.",
			)
			.optional(),
		chain: z
			.literal("ethereum")
			.describe(
				"Optional Xerberus chain identifier. Only ethereum is supported today; defaults to ethereum.",
			)
			.optional(),
		window: z
			.string()
			.describe(
				"Optional Xerberus data-window timestamp (ISO-8601). Pass the same value to every xerberus_* pack in a composite so all results come from one snapshot.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Xerberus liquidity-exit policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
