// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "arkham_counterparty" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Adaptive counterparty gate: allows routine payments to established counterparties whose amount and daily outflow match the wallet's historical baseline, and denies new recipients, anomalous amounts, and concentration or outflow spikes" as const;
export const PACK_LINK = "https://arkm.com" as const;
export const PACK_AUTHOR = "Arkham Intelligence" as const;
