// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: arkham_counterparty/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		require_known_counterparty: z
			.boolean()
			.describe(
				"When true, any destination absent from the sender's counterparty history denies outright, regardless of amount.",
			),
		max_new_counterparty_usd: z
			.number()
			.gte(0)
			.describe(
				"Cap in USD for a payment to a destination the sender has never transacted with. Only consulted when require_known_counterparty is false.",
			),
		min_counterparty_transactions: z
			.number()
			.gte(0)
			.describe(
				"Minimum number of prior transactions with a counterparty before the relationship counts as established.",
			),
		max_counterparty_last_seen_days: z
			.number()
			.gte(0)
			.describe(
				"Maximum days since the last interaction with this counterparty before the relationship is treated as stale and requires review.",
			),
		max_amount_vs_avg_multiple: z
			.number()
			.gte(0)
			.describe(
				"Maximum ratio of the proposed amount to the historical average transaction with this counterparty. 3 denies a payment more than 3x the usual size.",
			),
		max_counterparty_concentration_pct: z
			.number()
			.gte(0)
			.lte(100)
			.describe(
				"Maximum share (0-100) of the sender's recent activity that may be attributable to this single counterparty, catching sudden concentration spikes.",
			),
		max_outflow_vs_baseline_multiple: z
			.number()
			.gte(0)
			.describe(
				"Maximum ratio of recent daily outflow to the wallet's normal historical daily outflow. 2 denies when the wallet is moving more than twice its usual volume.",
			),
		max_data_age_seconds: z
			.number()
			.gte(0)
			.describe(
				"Maximum tolerated age of the Arkham observation. Null ages from the oracle fail-soft and do not trigger this rule.",
			),
	})
	.strict()
	.describe("Thresholds for the Arkham adaptive-counterparty gate")
	.strict();

export type Params = z.infer<typeof ParamsSchema>;

export const ParamsJsonSchema = {
	type: "object",
	description: "Thresholds for the Arkham adaptive-counterparty gate",
	properties: {
		require_known_counterparty: {
			type: "boolean",
			description:
				"When true, any destination absent from the sender's counterparty history denies outright, regardless of amount.",
		},
		max_new_counterparty_usd: {
			type: "number",
			minimum: 0,
			description:
				"Cap in USD for a payment to a destination the sender has never transacted with. Only consulted when require_known_counterparty is false.",
		},
		min_counterparty_transactions: {
			type: "number",
			minimum: 0,
			description:
				"Minimum number of prior transactions with a counterparty before the relationship counts as established.",
		},
		max_counterparty_last_seen_days: {
			type: "number",
			minimum: 0,
			description:
				"Maximum days since the last interaction with this counterparty before the relationship is treated as stale and requires review.",
		},
		max_amount_vs_avg_multiple: {
			type: "number",
			minimum: 0,
			description:
				"Maximum ratio of the proposed amount to the historical average transaction with this counterparty. 3 denies a payment more than 3x the usual size.",
		},
		max_counterparty_concentration_pct: {
			type: "number",
			minimum: 0,
			maximum: 100,
			description:
				"Maximum share (0-100) of the sender's recent activity that may be attributable to this single counterparty, catching sudden concentration spikes.",
		},
		max_outflow_vs_baseline_multiple: {
			type: "number",
			minimum: 0,
			description:
				"Maximum ratio of recent daily outflow to the wallet's normal historical daily outflow. 2 denies when the wallet is moving more than twice its usual volume.",
		},
		max_data_age_seconds: {
			type: "number",
			minimum: 0,
			description:
				"Maximum tolerated age of the Arkham observation. Null ages from the oracle fail-soft and do not trigger this rule.",
		},
	},
	required: [
		"require_known_counterparty",
		"max_new_counterparty_usd",
		"min_counterparty_transactions",
		"max_counterparty_last_seen_days",
		"max_amount_vs_avg_multiple",
		"max_counterparty_concentration_pct",
		"max_outflow_vs_baseline_multiple",
		"max_data_age_seconds",
	],
	additionalProperties: false,
} as const;
