// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: arkham_counterparty/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		sender_address: z
			.string()
			.describe(
				"The wallet initiating the payment (0x-prefixed). Its counterparty history and outflow baseline are what the policy measures against.",
			),
		destination_address: z
			.string()
			.describe(
				"The proposed recipient (0x-prefixed). Matched against the sender's known counterparties to decide whether this is an established relationship or a new one.",
			),
		chains: z
			.string()
			.describe(
				"Comma-separated Arkham chain identifiers scoping the counterparty and flow lookups (e.g. 'ethereum' or 'ethereum,base'). REQUIRED: unscoped, /flow/address returns every chain's full daily history - over 1MB for an active wallet, which exhausts the WASM heap. Scoping to one chain brings it to roughly 270KB.",
			),
		transaction_amount_usd: z
			.number()
			.gte(0)
			.describe(
				"USD notional of the proposed payment. CALLER-SUPPLIED and therefore NOT attested - see this pack's README. Defaults to 0 when omitted.",
			)
			.optional(),
		history_window_days: z
			.number()
			.gte(1)
			.lte(365)
			.describe(
				"Lookback window (1-365 days) for counterparty aggregation and the outflow baseline. Defaults to 90. Out-of-range values are rejected by the WASM, and the Rego then denies on the oracle error.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Arkham adaptive-counterparty policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
