// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "balancer" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Composite Balancer v3 pool risk gate: blocks deposits into pools with excessive token concentration, non-allowlisted tokens, boosted underlying protocol risk, low TVL, or sharp TVL drawdowns" as const;
export const PACK_LINK = "https://balancer.fi" as const;
export const PACK_AUTHOR = "" as const;
