// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: balancer/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		poolId: z.string().describe("Balancer pool identifier (the bytes32 pool id, 0x-prefixed)."),
		chain: z
			.string()
			.describe(
				"Balancer GraphQL GqlChain enum value naming the network the pool lives on (e.g. 'MAINNET', 'ARBITRUM', 'BASE').",
			),
		allowed_token_addresses: z
			.array(z.string())
			.describe(
				"Optional whitelist of token contract addresses (0x...). When non-empty, the Rego rule denies pools containing any token outside this set. Empty array disables the whitelist.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Balancer policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
