// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "xerberus_what_if" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Portfolio what-if gate: denies a transaction that pushes token concentration past a limit, raises HHI, erodes the share of the book exitable within 30 days, or lengthens the slowest exit beyond curator-set bounds" as const;
export const PACK_LINK = "https://xerberus.io" as const;
export const PACK_AUTHOR = "Xerberus" as const;
