// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: xerberus_what_if/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		wallets: z
			.array(z.string())
			.min(1)
			.max(10)
			.describe("Wallet addresses (0x-prefixed) that make up the managed portfolio."),
		add: z
			.array(
				z.object({
					token: z.string().describe("Token contract address (preferred) or symbol."),
					usd: z.number().gte(0).describe("USD amount added."),
				}),
			)
			.max(10)
			.describe(
				"Hypothetical additions to simulate. At least one of add or remove must be non-empty.",
			)
			.optional(),
		remove: z
			.array(
				z.object({
					token: z.string().describe("Token contract address (preferred) or symbol."),
					usd: z.number().gte(0).describe("USD amount removed."),
				}),
			)
			.max(10)
			.describe(
				"Hypothetical removals to simulate. A change with removals and no additions counts as risk-reducing.",
			)
			.optional(),
		impact_pct: z
			.number()
			.gte(0)
			.lte(100)
			.describe("Optional market-impact assumption in percent.")
			.optional(),
		chain: z
			.literal("ethereum")
			.describe(
				"Optional Xerberus chain identifier. Only ethereum is supported today; defaults to ethereum.",
			)
			.optional(),
		window: z
			.string()
			.describe(
				"Optional Xerberus data-window timestamp (ISO-8601). Pass the same value to every xerberus_* pack in a composite.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Xerberus portfolio what-if policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
