// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "arkham_entity" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Entity-aware spending gate: tiers a transaction limit by Arkham entity attribution, denying prohibited risk tags, unapproved entity categories, low-confidence attribution, and unlabelled destinations above an introductory cap" as const;
export const PACK_LINK = "https://arkm.com" as const;
export const PACK_AUTHOR = "Arkham Intelligence" as const;
