// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: arkham_entity/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		prohibited_tags: z
			.array(z.string())
			.describe(
				"Arkham behavioural tags that deny outright regardless of amount or attribution (e.g. 'sanctioned', 'hacker', 'scam', 'mixer'). Matched case-sensitively against the normalised tags the oracle emits.",
			),
		approved_entity_categories: z
			.array(z.string())
			.describe(
				"Arkham entity categories that qualify for the full verified tier (e.g. 'cex', 'custodian', 'defi'). An attributed address outside this set is capped at tier_unlabelled_max_usd.",
			),
		tier_verified_max_usd: z
			.number()
			.gte(0)
			.describe(
				"Hard ceiling in USD for any single transaction, applied even to a verified, approved-category destination.",
			),
		tier_unlabelled_max_usd: z
			.number()
			.gte(0)
			.describe(
				"Introductory cap in USD for destinations Arkham cannot attribute, and for attributed destinations outside approved_entity_categories.",
			),
		min_attribution_confidence: z
			.number()
			.gte(0)
			.lte(1)
			.describe(
				"Minimum Arkham attribution confidence (0-1) required to act on an entity match. A lower-confidence match denies, so a human can approve it out of band.",
			),
		deny_on_no_attribution: z
			.boolean()
			.describe(
				"When true, an address Arkham has no attribution for denies outright rather than falling back to tier_unlabelled_max_usd.",
			),
		max_risk_score: z
			.number()
			.gte(0)
			.lte(100)
			.describe("Maximum tolerated Arkham headline risk score (0-100) for the destination."),
		max_data_age_seconds: z
			.number()
			.gte(0)
			.describe(
				"Maximum tolerated age of the Arkham observation. A null age fails soft here; list data_age_seconds in deny_on_missing_fields to catch it instead.",
			),
		deny_on_missing_fields: z
			.array(z.enum(["attribution_confidence", "max_risk_score", "data_age_seconds"]))
			.describe(
				"Field names the oracle must actually report. A null on a listed field denies as missing_<field>; unlisted fields fail soft. An empty list opts out entirely. Arkham populates all three for an attributed address, so listing them is safe for curators who want an unreported value treated as a failure rather than a pass.",
			),
	})
	.strict()
	.describe("Thresholds for the Arkham entity-aware wallet gate")
	.strict();

export type Params = z.infer<typeof ParamsSchema>;

export const ParamsJsonSchema = {
	type: "object",
	description: "Thresholds for the Arkham entity-aware wallet gate",
	properties: {
		prohibited_tags: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Arkham behavioural tags that deny outright regardless of amount or attribution (e.g. 'sanctioned', 'hacker', 'scam', 'mixer'). Matched case-sensitively against the normalised tags the oracle emits.",
		},
		approved_entity_categories: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Arkham entity categories that qualify for the full verified tier (e.g. 'cex', 'custodian', 'defi'). An attributed address outside this set is capped at tier_unlabelled_max_usd.",
		},
		tier_verified_max_usd: {
			type: "number",
			minimum: 0,
			description:
				"Hard ceiling in USD for any single transaction, applied even to a verified, approved-category destination.",
		},
		tier_unlabelled_max_usd: {
			type: "number",
			minimum: 0,
			description:
				"Introductory cap in USD for destinations Arkham cannot attribute, and for attributed destinations outside approved_entity_categories.",
		},
		min_attribution_confidence: {
			type: "number",
			minimum: 0,
			maximum: 1,
			description:
				"Minimum Arkham attribution confidence (0-1) required to act on an entity match. A lower-confidence match denies, so a human can approve it out of band.",
		},
		deny_on_no_attribution: {
			type: "boolean",
			description:
				"When true, an address Arkham has no attribution for denies outright rather than falling back to tier_unlabelled_max_usd.",
		},
		max_risk_score: {
			type: "number",
			minimum: 0,
			maximum: 100,
			description: "Maximum tolerated Arkham headline risk score (0-100) for the destination.",
		},
		max_data_age_seconds: {
			type: "number",
			minimum: 0,
			description:
				"Maximum tolerated age of the Arkham observation. A null age fails soft here; list data_age_seconds in deny_on_missing_fields to catch it instead.",
		},
		deny_on_missing_fields: {
			type: "array",
			items: {
				type: "string",
				enum: ["attribution_confidence", "max_risk_score", "data_age_seconds"],
			},
			description:
				"Field names the oracle must actually report. A null on a listed field denies as missing_<field>; unlisted fields fail soft. An empty list opts out entirely. Arkham populates all three for an attributed address, so listing them is safe for curators who want an unreported value treated as a failure rather than a pass.",
		},
	},
	required: [
		"prohibited_tags",
		"approved_entity_categories",
		"tier_verified_max_usd",
		"tier_unlabelled_max_usd",
		"min_attribution_confidence",
		"deny_on_no_attribution",
		"max_risk_score",
		"max_data_age_seconds",
		"deny_on_missing_fields",
	],
	additionalProperties: false,
} as const;
