// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: arkham_entity/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		address: z
			.string()
			.describe("Destination address (0x-prefixed) to attribute and screen with Arkham."),
		chain: z
			.string()
			.describe(
				"Optional Arkham chain identifier (e.g. 'ethereum', 'base', 'arbitrum_one'). Arkham returns per-chain labels, tags and activity for the same address, so omitting this widens the lookup to every supported chain.",
			)
			.optional(),
		transaction_amount_usd: z
			.number()
			.gte(0)
			.describe(
				"USD notional of the proposed transaction, used by the Rego tiering rules. CALLER-SUPPLIED and therefore NOT attested - see this pack's README. Defaults to 0 when omitted, which places the transaction in the most permissive tier.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Arkham entity-aware wallet policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
