// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, GatewayEnv } from "./deployment";
import type { KnownPackId } from "./known-pack-ids";

export const AUDITED_POLICY_DATA = {
	balancer: {
		"1": {
			prod: "0xAd60980C077123A82c574624AC857Dc775b914bd",
		},
		"8453": {
			prod: "0x53F172A3Aa5C997f0F3CD62Af032FefCab754C42",
		},
		"84532": {
			prod: "0x245819bE9518a4282D8EA72c82ca853131a87d4c",
		},
		"11155111": {
			prod: "0xA9562499f32BC3570f234fF184B6D90585D0d02F",
		},
	},
	blockaid: {
		"1": {
			prod: "0xa7ab76E81269f48b6C40132d2234A710b0B7A099",
		},
		"8453": {
			prod: "0x33394324EA2a7a599B368bd73133cc02c1E04753",
		},
		"84532": {
			prod: "0xa086D57d33d030A5209fED5f62be0014f09B0413",
		},
		"11155111": {
			prod: "0x849b66977Ac8aCEB246A6b42379F2df4cD6a8DD1",
		},
	},
	chainalysis: {
		"1": {
			prod: "0xCacbdEDA32C0048bbE0Ae0d3081Ced3490699049",
		},
		"8453": {
			prod: "0xceB2027a5fA390740971c7cbb2523841C19CC2f9",
		},
		"84532": {
			prod: "0xdC2e9d30B8e415F907e39f0bfe22974B9894740F",
		},
		"11155111": {
			prod: "0x226d196d565b92952669701Fb6cb85B586706996",
		},
	},
	guardrail: {
		"1": {
			prod: "0x0953fdC0Ccd8fF98D81B0972F95a94E5815Efb78",
		},
		"8453": {
			prod: "0x194FD071bED2DaCCe87ef879d3E8CA271c34b791",
		},
		"84532": {
			prod: "0x91e535846ca509D5654DE743081EaF7aCF6E7314",
		},
		"11155111": {
			prod: "0xFca31181ACc0BfECF88E8D58281dB54282313094",
		},
	},
	persona: {
		"1": {
			prod: "0x85C946F218C00095885ba418bc3F802aE8dD16B0",
		},
		"8453": {
			prod: "0x3c1cFEa7E26059eE8e88E4A04588C7b191D48Bc1",
		},
		"84532": {
			prod: "0xA3aDce2bcAf62dfd945D627cCfD563158e09eC53",
		},
		"11155111": {
			prod: "0x87C4AFf01D7bABAcaC791af4e9b2FB44637cFe10",
		},
	},
	redstone: {
		"1": {
			prod: "0xc81371B54F5d71E8aA92a3601f30f3520c34A5a9",
		},
		"8453": {
			prod: "0xa5aDDdcf0d37C50A338B3C7F8067FB175AFAf6Bf",
		},
		"84532": {
			prod: "0xDbfE2fea061e71109e65e511CD11D070f49A187d",
		},
		"11155111": {
			prod: "0x6621D7F739a3682054ac974D772AEEBb8548b1BF",
		},
	},
	sumsub: {
		"1": {
			prod: "0x6B8d613bD3003A6e90F1536C576519A231730A1d",
		},
		"8453": {
			prod: "0x271221cd3bfF4f45b41A28Af4A28a82F4e373265",
		},
		"84532": {
			prod: "0x52458F0F5937b703d64B5D206a800384A7fc59e1",
		},
		"11155111": {
			prod: "0xa8Dd24EC989CD9Fc5FbFa3fe2B7991A053753E11",
		},
	},
	vaultsfyi: {
		"1": {
			prod: "0xd0947ba40e526E7cdD9d2f9C276cED1B2e089c49",
		},
		"8453": {
			prod: "0x763800149600164edBd19d0eeE9f858d7ac27836",
		},
		"84532": {
			prod: "0x443487D506eEc522e5fb5075eBDbD7496DB454dF",
		},
		"11155111": {
			prod: "0x90ef32c7D103D5Af2A546f94BdA994BC37372017",
		},
	},
	webacy: {
		"1": {
			prod: "0xc127976860eEF5FF5d610548C456ABFEE66CD620",
		},
		"8453": {
			prod: "0x031afeF4c77774960Eb33fb446F9Ce3612C56b5c",
		},
		"84532": {
			prod: "0x01206E5302794Fba1B71b761594a5e8b4111Be60",
		},
		"11155111": {
			prod: "0xBFf38a5A77262ADfC10667004A550337A97EFB36",
		},
	},
} as const satisfies Readonly<
	Record<
		KnownPackId,
		Readonly<Partial<Record<ChainId, Readonly<Partial<Record<GatewayEnv, string>>>>>>
	>
>;
