// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: repo-root deployments.json (run `pnpm gen:bindings` to regenerate).
import type { ChainId, GatewayEnv } from "./deployment";
import type { KnownPackId } from "./known-pack-ids";

/**
 * Audited on-chain `policyData` address for each first-party pack per
 * (chainId, env), prod env only. Read by `classifyProvenance` (provenance.ts)
 * to tell Newton's audited pack from a curator lookalike. NOT a compose-time
 * gate. Regenerated by `pnpm gen:bindings` from the repo-root deployments.json.
 */
export const AUDITED_POLICY_DATA: Readonly<
	Record<KnownPackId, Readonly<Partial<Record<ChainId, Readonly<Partial<Record<GatewayEnv, string>>>>>>>
> = {
	balancer: {},
	blockaid: {},
	chainalysis: {},
	guardrail: {},
	persona: {},
	redstone: {},
	sumsub: {},
	vaultsfyi: {},
	webacy: {},
};
