// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "pharos_treasury" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Risk-adjusted stablecoin treasury gate: admits a stablecoin only when there is no active depeg, stress is below threshold, the redemption route is approved, and exit capacity comfortably exceeds the resulting position" as const;
export const PACK_LINK = "https://pharos.watch" as const;
export const PACK_AUTHOR = "Pharos" as const;
