// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: pharos_treasury/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		deny_on_active_depeg: z
			.boolean()
			.describe("Deny while Pharos reports a confirmed active depeg incident for the asset."),
		max_peg_deviation_bps: z
			.number()
			.gte(0)
			.describe(
				"Maximum tolerated absolute deviation from the peg target, in basis points. Catches an asset drifting off peg before an incident is formally declared.",
			),
		max_stress_score: z
			.number()
			.gte(0)
			.lte(100)
			.describe(
				"Maximum tolerated Pharos stress score (0-100). Stress is the earlier and broader signal, rising before a full depeg.",
			),
		require_redemption: z
			.boolean()
			.describe(
				"When true, the asset must have a working direct redemption route. When false, redemption is only checked if a route is reported.",
			),
		approved_redemption_route_families: z
			.array(z.string())
			.describe(
				"Pharos redemption route families the curator will accept (e.g. 'issuer-direct', 'authorised-participant'). An asset redeeming through anything else denies.",
			),
		approved_access_models: z
			.array(z.string())
			.describe(
				"Pharos redemption access models the curator will accept (e.g. 'permissionless', 'kyc-gated'). Governs WHO may redeem, not how.",
			),
		required_route_status: z
			.string()
			.describe(
				"The redemption route status the asset must report. Pharos reports 'open' for a working route - NOT 'active'.",
			),
		min_exit_capacity_multiple: z
			.number()
			.gte(0)
			.describe(
				"Minimum ratio of sellable-without-excess-slippage capacity to the resulting position. 3 requires the treasury be able to exit three times the position it is taking on.",
			),
		min_liquidity_score: z
			.number()
			.gte(0)
			.lte(100)
			.describe(
				"Minimum Pharos DEX liquidity score (0-100), summarising depth and quality of available exit liquidity.",
			),
		max_data_age_seconds: z
			.number()
			.gte(0)
			.describe(
				"Maximum tolerated age of the Pharos observation, taken as the OLDEST across all sources. These move on very different clocks: price and stress refresh in minutes, but dex-liquidity-history is a DAILY bucket (up to ~24h) and redemption-backstops lags by hours. A ceiling below ~24h will deny permanently on the slow feeds. Per-source ages are emitted separately for diagnosis. Null ages fail soft.",
			),
	})
	.strict()
	.describe("Thresholds for the Pharos risk-adjusted treasury gate")
	.strict();

export type Params = z.infer<typeof ParamsSchema>;

export const ParamsJsonSchema = {
	type: "object",
	description: "Thresholds for the Pharos risk-adjusted treasury gate",
	properties: {
		deny_on_active_depeg: {
			type: "boolean",
			description: "Deny while Pharos reports a confirmed active depeg incident for the asset.",
		},
		max_peg_deviation_bps: {
			type: "number",
			minimum: 0,
			description:
				"Maximum tolerated absolute deviation from the peg target, in basis points. Catches an asset drifting off peg before an incident is formally declared.",
		},
		max_stress_score: {
			type: "number",
			minimum: 0,
			maximum: 100,
			description:
				"Maximum tolerated Pharos stress score (0-100). Stress is the earlier and broader signal, rising before a full depeg.",
		},
		require_redemption: {
			type: "boolean",
			description:
				"When true, the asset must have a working direct redemption route. When false, redemption is only checked if a route is reported.",
		},
		approved_redemption_route_families: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Pharos redemption route families the curator will accept (e.g. 'issuer-direct', 'authorised-participant'). An asset redeeming through anything else denies.",
		},
		approved_access_models: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Pharos redemption access models the curator will accept (e.g. 'permissionless', 'kyc-gated'). Governs WHO may redeem, not how.",
		},
		required_route_status: {
			type: "string",
			description:
				"The redemption route status the asset must report. Pharos reports 'open' for a working route - NOT 'active'.",
		},
		min_exit_capacity_multiple: {
			type: "number",
			minimum: 0,
			description:
				"Minimum ratio of sellable-without-excess-slippage capacity to the resulting position. 3 requires the treasury be able to exit three times the position it is taking on.",
		},
		min_liquidity_score: {
			type: "number",
			minimum: 0,
			maximum: 100,
			description:
				"Minimum Pharos DEX liquidity score (0-100), summarising depth and quality of available exit liquidity.",
		},
		max_data_age_seconds: {
			type: "number",
			minimum: 0,
			description:
				"Maximum tolerated age of the Pharos observation, taken as the OLDEST across all sources. These move on very different clocks: price and stress refresh in minutes, but dex-liquidity-history is a DAILY bucket (up to ~24h) and redemption-backstops lags by hours. A ceiling below ~24h will deny permanently on the slow feeds. Per-source ages are emitted separately for diagnosis. Null ages fail soft.",
		},
	},
	required: [
		"deny_on_active_depeg",
		"max_peg_deviation_bps",
		"max_stress_score",
		"require_redemption",
		"approved_redemption_route_families",
		"approved_access_models",
		"required_route_status",
		"min_exit_capacity_multiple",
		"min_liquidity_score",
		"max_data_age_seconds",
	],
	additionalProperties: false,
} as const;
