// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: pharos_treasury/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		stablecoin_id: z
			.string()
			.describe(
				"Canonical Pharos stablecoin identifier in ticker-issuer form, e.g. 'usdc-circle'. This is the key every Pharos endpoint is queried on.",
			),
		transaction_amount_usd: z
			.number()
			.gte(0)
			.describe(
				"USD notional of the proposed acquisition, used to size the position against available exit liquidity. CALLER-SUPPLIED and therefore NOT attested - see this pack's README. Defaults to 0 when omitted, which makes the exit-capacity ratio undefined and fail-soft.",
			)
			.optional(),
		stress_lookback_days: z
			.number()
			.gte(1)
			.lte(365)
			.describe("Lookback window in days for the Pharos stress-signal history. Defaults to 7.")
			.optional(),
		max_cost_bps: z
			.number()
			.gte(1)
			.lte(10000)
			.describe(
				"Maximum acceptable execution cost in basis points when sizing exit liquidity. Compared against each capacity-curve rung's ACTUAL executionCostBps (a deep stablecoin prices around 9-10bps), NOT against the 200bps bound Pharos runs its simulations under. Defaults to 50.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Pharos risk-adjusted treasury policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
