// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"11155111": {
		policy: "0xdc9a01c944fCA72c1513B612DC03Eef41815fF8f",
		policyData: "0x2Cd30c93c89acBa33Dbe0184e0E1617C94B19Ee9",
		wasmCid: "bafybeih4cuqqqwfzd6alg2pqik74my6hloyqlsbdu4i2fm23ykfzalw66a",
		policyCodeHash: "0x73ad7eda7415e5a8754e9dbf9ca22d6f27848daae436a26f13befc056fa7d96d",
		deployedAt: "2026-06-09",
		notes: "host-secrets fix; current",
	},
} as const satisfies Record<ChainId, Deployment>;
