// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment, GatewayEnv } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"1": {
		prod: {
			policyData: "0xc81371B54F5d71E8aA92a3601f30f3520c34A5a9",
			wasmCid: "bafybeietgew4k4kfztjgdny6ujwsxvuu4zusghsvh6rqbs6pwme7w7lh3e",
			policyCodeHash: "0xfc83b3204c9119d8cbd3d59b560805f4415a2b1539b87dab128e1943c05ed462",
			deployedAt: "2026-06-21",
		},
	},
	"8453": {
		prod: {
			policyData: "0xa5aDDdcf0d37C50A338B3C7F8067FB175AFAf6Bf",
			wasmCid: "bafybeietgew4k4kfztjgdny6ujwsxvuu4zusghsvh6rqbs6pwme7w7lh3e",
			policyCodeHash: "0xfc83b3204c9119d8cbd3d59b560805f4415a2b1539b87dab128e1943c05ed462",
			deployedAt: "2026-06-20",
		},
	},
	"84532": {
		prod: {
			policyData: "0xDbfE2fea061e71109e65e511CD11D070f49A187d",
			wasmCid: "bafybeietgew4k4kfztjgdny6ujwsxvuu4zusghsvh6rqbs6pwme7w7lh3e",
			policyCodeHash: "0xfc83b3204c9119d8cbd3d59b560805f4415a2b1539b87dab128e1943c05ed462",
			deployedAt: "2026-06-16",
		},
	},
	"11155111": {
		prod: {
			policyData: "0x6621D7F739a3682054ac974D772AEEBb8548b1BF",
			wasmCid: "bafybeietgew4k4kfztjgdny6ujwsxvuu4zusghsvh6rqbs6pwme7w7lh3e",
			policyCodeHash: "0xfc83b3204c9119d8cbd3d59b560805f4415a2b1539b87dab128e1943c05ed462",
			deployedAt: "2026-06-16",
		},
	},
} as const satisfies Readonly<
	Partial<Record<ChainId, Readonly<Partial<Record<GatewayEnv, Deployment>>>>>
>;
