// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "redstone" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Gates vault deposits when the on-chain price oracle diverges from RedStone's market price beyond a configured threshold" as const;
export const PACK_LINK = "https://redstone.finance" as const;
export const PACK_AUTHOR = "" as const;
