// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: redstone/secrets_schema.json
import { z } from "zod";

export const SecretsSchema = z.object({}).strict();

export type Secrets = z.infer<typeof SecretsSchema>;
