// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: redstone/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		symbol: z
			.string()
			.describe("Asset symbol the off-chain RedStone feed quotes (e.g. 'ETH', 'BTC')."),
		provider: z
			.string()
			.describe("RedStone provider name. Defaults to 'redstone' when omitted.")
			.optional(),
		rpcUrl: z
			.string()
			.describe(
				"Ethereum-compatible JSON-RPC endpoint used to call the on-chain comparison oracle.",
			),
		onchainOracle: z
			.object({
				address: z.string().describe("Oracle contract address (0x-prefixed)."),
				selector: z
					.string()
					.describe(
						"4-byte function selector to call on the oracle (0x-prefixed). Typically the latest-answer accessor.",
					),
				decimals: z
					.number()
					.int()
					.describe(
						"Number of decimals the oracle's return value is scaled by. Defaults to 18 when omitted.",
					)
					.optional(),
			})
			.describe("On-chain oracle the WASM compares the RedStone price against."),
		prevSnapshot: z
			.union([
				z
					.object({
						divergenceBp: z
							.number()
							.describe("Divergence (in basis points) recorded in the previous evaluation.")
							.optional(),
						timestampMs: z
							.number()
							.describe("Unix timestamp (ms) of the previous evaluation.")
							.optional(),
					})
					.describe(
						"Optional prior divergence snapshot used to compute sustained-divergence duration. Set to null on the first evaluation.",
					),
				z
					.null()
					.describe(
						"Optional prior divergence snapshot used to compute sustained-divergence duration. Set to null on the first evaluation.",
					),
			])
			.describe(
				"Optional prior divergence snapshot used to compute sustained-divergence duration. Set to null on the first evaluation.",
			)
			.optional(),
	})
	.describe("Inputs passed to the RedStone oracle-divergence policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
