// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "pharos_safe_mode" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Graduated stablecoin safe-mode gate: when Pharos reports elevated stress or an active depeg, blocks exposure-increasing actions while continuing to permit withdrawals, redemptions, and swaps into curator-approved safer assets" as const;
export const PACK_LINK = "https://pharos.watch" as const;
export const PACK_AUTHOR = "Pharos" as const;
