// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: pharos_safe_mode/secrets_schema.json
import { z } from "zod";

export const SecretsSchema = z
	.object({
		PHAROS_API_KEY: z
			.string()
			.min(1)
			.describe("Pharos API key, sent as the X-API-Key request header."),
	})
	.strict();

export type Secrets = z.infer<typeof SecretsSchema>;
