// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: pharos_safe_mode/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		stablecoin_id: z
			.string()
			.describe(
				"Canonical Pharos stablecoin identifier in ticker-issuer form, e.g. 'usdc-circle'.",
			),
		stress_lookback_days: z
			.number()
			.gte(1)
			.lte(365)
			.describe("Lookback window in days for the Pharos stress-signal history. Defaults to 7.")
			.optional(),
		flow_window_hours: z
			.number()
			.gte(1)
			.lte(720)
			.describe("Window in hours for the mint/burn flow-anomaly lookup. Defaults to 24.")
			.optional(),
	})
	.describe("Inputs passed to the Pharos stablecoin safe-mode policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
