export const POLICY_DATA_ABI = [
  {
    type: 'function',
    name: 'attest',
    inputs: [
      {
        name: 'policyData',
        type: 'tuple',
        internalType: 'struct NewtonMessage.PolicyData',
        components: [
          { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
          { name: 'data', type: 'bytes', internalType: 'bytes' },
          { name: 'attestation', type: 'bytes', internalType: 'bytes' },
          { name: 'policyDataAddress', type: 'address', internalType: 'address' },
          { name: 'expireBlock', type: 'uint32', internalType: 'uint32' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'factory',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAttestationInfo',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct INewtonPolicyData.AttestationInfo',
        components: [
          { name: 'attesters', type: 'address[]', internalType: 'address[]' },
          { name: 'attestationType', type: 'uint8', internalType: 'enum INewtonPolicyData.AttestationType' },
          { name: 'verifier', type: 'address', internalType: 'address' },
          { name: 'verificationKey', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getExpireAfter',
    inputs: [],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMetadataCid',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSecretsSchemaCid',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getWasmCid',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: '_factory', type: 'address', internalType: 'address' },
      { name: 'wasmCid', type: 'string', internalType: 'string' },
      { name: 'secretsSchemaCid', type: 'string', internalType: 'string' },
      { name: 'expireAfter', type: 'uint32', internalType: 'uint32' },
      { name: 'metadataCid', type: 'string', internalType: 'string' },
      { name: '_owner', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isPolicyDataVerified',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAttestationInfo',
    inputs: [
      {
        name: 'attestationInfo',
        type: 'tuple',
        internalType: 'struct INewtonPolicyData.AttestationInfo',
        components: [
          { name: 'attesters', type: 'address[]', internalType: 'address[]' },
          { name: 'attestationType', type: 'uint8', internalType: 'enum INewtonPolicyData.AttestationType' },
          { name: 'verifier', type: 'address', internalType: 'address' },
          { name: 'verificationKey', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMetadataCid',
    inputs: [{ name: 'metadataCid', type: 'string', internalType: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setSecretsSchemaCid',
    inputs: [{ name: 'secretsSchemaCid', type: 'string', internalType: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AttestationInfoUpdated',
    inputs: [
      {
        name: 'attestationInfo',
        type: 'tuple',
        indexed: false,
        internalType: 'struct INewtonPolicyData.AttestationInfo',
        components: [
          { name: 'attesters', type: 'address[]', internalType: 'address[]' },
          { name: 'attestationType', type: 'uint8', internalType: 'enum INewtonPolicyData.AttestationType' },
          { name: 'verifier', type: 'address', internalType: 'address' },
          { name: 'verificationKey', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [{ name: 'version', type: 'uint8', indexed: false, internalType: 'uint8' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PolicyDataMetadataCidUpdated',
    inputs: [{ name: 'metadataCid', type: 'string', indexed: false, internalType: 'string' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SecretsSchemaCidUpdated',
    inputs: [{ name: 'secretsSchemaCid', type: 'string', indexed: false, internalType: 'string' }],
    anonymous: false,
  },
  { type: 'error', name: 'InterfaceNotSupported', inputs: [] },
  { type: 'error', name: 'InvalidAttestationInfo', inputs: [] },
  { type: 'error', name: 'InvalidPolicyData', inputs: [{ name: 'data', type: 'bytes', internalType: 'bytes' }] },
  { type: 'error', name: 'InvalidSignature', inputs: [] },
  { type: 'error', name: 'OnlyNewtonPolicy', inputs: [] },
  { type: 'error', name: 'SignatureVerificationFailed', inputs: [] },
];
