// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"11155111": {
		policy: "0xdCAb384d6BF6FE895b47c3e56AbEf1e8C37c1f98",
		policyData: "0x2A88fbA00B35D0ae478458300496F8C6479724EB",
		wasmCid: "bafybeibmjxiq6ulffjnmthcbqqwkj3hdkdw4lybytdzr5k2zqndtds4ceu",
		policyCodeHash: "0x35162b281b4f41cbac131f602fd9b485f9dbae9cdb411b9465132521ddcca10a",
		deployedAt: "2026-06-09",
		notes: "host-secrets fix; current",
	},
} as const satisfies Readonly<Partial<Record<ChainId, Deployment>>>;
