// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"11155111": {
		policy: "0x005bC8ddF9a27DbC7b2Fa250c413a5E794cad873",
		policyData: "0x2De2bfe212ec11D9a7E9F3125662c38e8efaA91C",
		wasmCid: "bafybeigk7pjxtkbrnlqg7yixoms3ykjogsicrrgsihh35nyvk54cgxvrla",
		policyCodeHash: "0x4b2f9b84045794a10fed8bd980f7e1c2893b31ddb9039496c6c716676584a9c6",
		deployedAt: "2026-06-14",
		notes: "Phase 0 Stream D — composite namespacing redeploy",
	},
} as const satisfies Readonly<Partial<Record<ChainId, Deployment>>>;
