// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "sumsub" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Gates vault deposits behind SumSub KYC: requires a passing applicant review (GREEN), allowed country, minimum age, and non-stale verification." as const;
export const PACK_LINK = "https://sumsub.com" as const;
export const PACK_AUTHOR = "" as const;
