// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: sumsub/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		max_age_days: z
			.number()
			.describe(
				"Maximum age (in days, since the SumSub applicant record was created) before KYC is considered stale and must be re-verified.",
			),
		allowed_countries: z
			.array(z.string())
			.describe(
				'Allow-list of ISO 3166-1 alpha-2 country codes (e.g. "US","GB"). If the applicant\'s country is not in this list the deposit is denied.',
			),
		min_age_years: z
			.number()
			.describe("Minimum applicant age in whole years derived from the SumSub date of birth."),
		required_review_answer: z
			.string()
			.describe(
				'The SumSub reviewAnswer value required to pass (typically "GREEN"). Any other value ("RED" or unset) denies.',
			),
		deny_on_pending: z
			.boolean()
			.describe(
				"If true, deny while the applicant's reviewStatus is one of init/pending/prechecked/queued. If false, pending applicants are not denied solely on pending state (review_status_not_passing may still deny them via review_answer).",
			),
	})
	.describe("KYC gating thresholds for SumSub-backed vault deposits");

export type Params = z.infer<typeof ParamsSchema>;
