// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: sumsub/secrets_schema.json
import { z } from "zod";

export const SecretsSchema = z
	.object({ SUMSUB_APP_TOKEN: z.string().min(1), SUMSUB_SECRET_KEY: z.string().min(1) })
	.strict();

export type Secrets = z.infer<typeof SecretsSchema>;
