// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"11155111": {
		policy: "0x74cF1FB7324fBb0F680Fb1fB5561e19205771D73",
		policyData: "0x4408128a4A214DE0dd3587b8D96c5DDf5Ae24367",
		wasmCid: "bafybeiatha7peyy7mhs6btlytvfsaz6ciywo65rkkmaieqp77vusalc7ly",
		policyCodeHash: "0x0806d9a91b1aa6e7ef6da8ecd6dde4a2ef553c232f18ee02f11a266528417392",
		deployedAt: "2026-06-09",
		notes: "host-secrets fix; current",
	},
} as const satisfies Record<ChainId, Deployment>;
