// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "guardrail" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Gates vault deposits when Guardrail.so reports active high/critical alerts on the target protocol or the protocol's health score is below floor" as const;
export const PACK_LINK = "https://guardrail.so" as const;
export const PACK_AUTHOR = "" as const;
