// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: guardrail/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		deny_on_active_alert: z
			.boolean()
			.describe("Deny when any active alert on the target has a severity in deny_alert_severities"),
		deny_alert_severities: z
			.array(z.string())
			.describe("Lowercased severity strings that trigger a deny (e.g. ['critical','high'])"),
		max_alert_age_seconds: z
			.number()
			.describe(
				"Maximum allowed age (seconds) for the oldest active alert. Beyond this, alert data itself is treated as stale and the deposit denies.",
			),
		min_health_score: z
			.number()
			.describe(
				"Minimum acceptable Guardrail health score. Only enforced when health_available is true.",
			),
	})
	.describe("Thresholds for the Guardrail on-chain monitoring gate");

export type Params = z.infer<typeof ParamsSchema>;
