// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: guardrail/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		protocolId: z
			.string()
			.describe(
				"Guardrail protocol identifier. Used as the alert/health target when no vault address is supplied.",
			)
			.optional(),
		vaultAddress: z
			.string()
			.describe(
				"Vault contract address (0x-prefixed). Preferred target when both fields are present.",
			)
			.optional(),
		chainId: z
			.number()
			.int()
			.describe(
				"EVM chain id of the target (e.g. 1 for mainnet). Optional; passed through to the Guardrail API as a filter.",
			)
			.optional(),
	})
	.and(z.union([z.any(), z.any()]))
	.describe(
		"Inputs passed to the Guardrail policy WASM at evaluation time. At least one of `protocolId` or `vaultAddress` is required.",
	);

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
