// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "arkham_risk" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Explainable risk gate: denies direct or near-hop exposure to curator-configured severe risk categories, escalates distant exposure only when materially large or recent, tolerates configured dust, and names the offending transaction path in the deny reason" as const;
export const PACK_LINK = "https://arkm.com" as const;
export const PACK_AUTHOR = "Arkham Intelligence" as const;
