// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: arkham_risk/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		severe_categories: z
			.array(z.string())
			.describe(
				"Risk categories treated as severe (e.g. 'sanctions', 'hacker', 'ransomware', 'mixer', 'darkweb'). Only exposure in these categories can trigger the hop, materiality and recency rules.",
			),
		max_severe_hop_distance: z
			.number()
			.gte(0)
			.describe(
				"Exposure to a severe category within this many transaction hops denies outright, at any value above the dust floor. 1 means direct and one-hop exposure deny.",
			),
		material_exposure_usd: z
			.number()
			.gte(0)
			.describe(
				"Beyond max_severe_hop_distance, severe exposure denies only once the contributed USD value exceeds this threshold.",
			),
		recent_exposure_days: z
			.number()
			.gte(0)
			.describe(
				"Beyond max_severe_hop_distance, severe exposure also denies when the most recent linking transaction is within this many days, regardless of value.",
			),
		dust_tolerance_usd: z
			.number()
			.gte(0)
			.describe(
				"Paths contributing at or below this USD value are ignored entirely, so dusting attacks cannot brick a wallet. Set to 0 to consider every path.",
			),
		deny_on_seed: z
			.boolean()
			.describe(
				"When true, deny if the address is itself a known risky source rather than merely exposed to one.",
			),
		max_risk_score: z
			.number()
			.gte(0)
			.lte(100)
			.describe(
				"Maximum tolerated Arkham headline risk score (0-100), applied independently of the path analysis.",
			),
		max_data_age_seconds: z
			.number()
			.gte(0)
			.describe(
				"Maximum tolerated age of the Arkham observation. Null ages from the oracle fail-soft and do not trigger this rule.",
			),
	})
	.strict()
	.describe("Thresholds for the Arkham explainable-risk gate")
	.strict();

export type Params = z.infer<typeof ParamsSchema>;

export const ParamsJsonSchema = {
	type: "object",
	description: "Thresholds for the Arkham explainable-risk gate",
	properties: {
		severe_categories: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Risk categories treated as severe (e.g. 'sanctions', 'hacker', 'ransomware', 'mixer', 'darkweb'). Only exposure in these categories can trigger the hop, materiality and recency rules.",
		},
		max_severe_hop_distance: {
			type: "number",
			minimum: 0,
			description:
				"Exposure to a severe category within this many transaction hops denies outright, at any value above the dust floor. 1 means direct and one-hop exposure deny.",
		},
		material_exposure_usd: {
			type: "number",
			minimum: 0,
			description:
				"Beyond max_severe_hop_distance, severe exposure denies only once the contributed USD value exceeds this threshold.",
		},
		recent_exposure_days: {
			type: "number",
			minimum: 0,
			description:
				"Beyond max_severe_hop_distance, severe exposure also denies when the most recent linking transaction is within this many days, regardless of value.",
		},
		dust_tolerance_usd: {
			type: "number",
			minimum: 0,
			description:
				"Paths contributing at or below this USD value are ignored entirely, so dusting attacks cannot brick a wallet. Set to 0 to consider every path.",
		},
		deny_on_seed: {
			type: "boolean",
			description:
				"When true, deny if the address is itself a known risky source rather than merely exposed to one.",
		},
		max_risk_score: {
			type: "number",
			minimum: 0,
			maximum: 100,
			description:
				"Maximum tolerated Arkham headline risk score (0-100), applied independently of the path analysis.",
		},
		max_data_age_seconds: {
			type: "number",
			minimum: 0,
			description:
				"Maximum tolerated age of the Arkham observation. Null ages from the oracle fail-soft and do not trigger this rule.",
		},
	},
	required: [
		"severe_categories",
		"max_severe_hop_distance",
		"material_exposure_usd",
		"recent_exposure_days",
		"dust_tolerance_usd",
		"deny_on_seed",
		"max_risk_score",
		"max_data_age_seconds",
	],
	additionalProperties: false,
} as const;
