// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: arkham_risk/secrets_schema.json
import { z } from "zod";

export const SecretsSchema = z
	.object({
		ARKHAM_API_KEY: z
			.string()
			.min(1)
			.describe("Arkham Intelligence API key, sent as the API-Key request header."),
	})
	.strict();

export type Secrets = z.infer<typeof SecretsSchema>;
