// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: arkham_risk/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		address: z
			.string()
			.describe("Address (0x-prefixed) to screen for risk exposure and to trace risk paths for."),
		chain: z
			.string()
			.describe(
				"Optional Arkham chain identifier. Arkham scores the same address differently per chain, so omitting this aggregates across every supported network.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Arkham explainable-risk policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
