// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment, GatewayEnv } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"11155111": {
		stagef: {
			policy: "0x7eC92AfEdcf2DB90222f04044C47ce0Efd7ccbcc",
			policyData: "0x9242fc89033C612878e64CcDF6d1Fff8b0d1fC37",
			wasmCid: "bafybeibiqon7wsceuet2lumtsu6364vnbe6ezwwwtjlnpusclorai3s5nm",
			policyCodeHash: "0x78067d1329f7cf28fff8728da6f1480a047dde458c04fa8db69407bc7bcb492b",
			deployedAt: "2026-06-14",
			notes: "Phase 0 Stream D — composite namespacing redeploy",
		},
	},
} as const satisfies Readonly<
	Partial<Record<ChainId, Readonly<Partial<Record<GatewayEnv, Deployment>>>>>
>;
