// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "vaultsfyi" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Gates vault deposits based on real-time risk signals: APY anomalies, TVL drawdowns, risk score floors, and allocation changes" as const;
export const PACK_LINK = "https://vaults.fyi" as const;
export const PACK_AUTHOR = "" as const;
