// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: vaultsfyi/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		apy_z_max: z
			.number()
			.describe(
				"Max APY z-score (current vs 30d median). Exceeding this indicates an APY anomaly.",
			),
		tvl_drawdown_24h_max_pct: z.number().describe("Max allowed 24h TVL drawdown percentage"),
		tvl_drawdown_7d_max_pct: z.number().describe("Max allowed 7d TVL drawdown percentage"),
		risk_score_floor: z.number().describe("Minimum acceptable risk score (0-1 scale)"),
		deny_on_allocation_change: z
			.boolean()
			.describe(
				"Whether to deny if vault allocation/strategy metadata has changed since last evaluation",
			),
		deny_on_critical_flag: z
			.boolean()
			.describe("Whether to deny if the vault has a flag with severity 'critical' or 'high'"),
		deny_on_corrupted: z
			.boolean()
			.describe("Whether to deny if the vault is reported as corrupted by the data source"),
	})
	.describe("Risk envelope thresholds for vault deposit gating");

export type Params = z.infer<typeof ParamsSchema>;
