// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: vaultsfyi/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		network: z
			.string()
			.describe(
				"Blockchain network name as accepted by the vaults.fyi API (e.g. 'mainnet', 'base', 'arbitrum').",
			),
		vaultAddress: z.string().describe("Vault contract address (0x-prefixed) to inspect."),
		lastKnownAllocationHash: z
			.union([
				z
					.string()
					.describe(
						"Hash of the previously observed allocation. Used to detect changes between evaluations. Null on the first evaluation.",
					),
				z
					.null()
					.describe(
						"Hash of the previously observed allocation. Used to detect changes between evaluations. Null on the first evaluation.",
					),
			])
			.describe(
				"Hash of the previously observed allocation. Used to detect changes between evaluations. Null on the first evaluation.",
			)
			.optional(),
	})
	.describe("Inputs passed to the vaults.fyi allocation-change policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
