/**
 * Generates TypeScript bindings for every Newton policy pack in this
 * monorepo. Iterates the AVS-side pack directories at the repo root
 * (`<pack>/{wasm_args_schema.json, secrets_schema.json, params_schema.json,
 * policy_metadata.json}`) and emits per-package bindings into
 * `packages/policy-pack-<name>/src/`.
 *
 * Run with `pnpm gen:bindings` (from the repo root).
 *
 * The generated `src/*` files all carry an AUTO-GENERATED banner — never
 * hand-edit them. The per-package `package.json`, `tsconfig.json`, and
 * `tsup.config.ts` are scaffolded once and not overwritten on regen, so
 * pack maintainers can hand-tune them (e.g. add a custom prepare-query
 * dep) without losing their work.
 *
 * History: retargeted from PR #25's `sdk/scripts/generate-packs.ts` (Alec
 * Savvy) per NEWT-1457. Original emitted into a single `sdk/src/packs/`
 * subtree; this version emits into one workspace per pack so each
 * publishes independently as `@newton-xyz/policy-pack-<name>`.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { jsonSchemaToZod } from "json-schema-to-zod";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const PACKAGES_DIR = path.join(REPO_ROOT, "packages");
const SHARED_PACKAGE_DIR = path.join(PACKAGES_DIR, "policy-pack-shared");

const SCHEMA_FILES = [
	"wasm_args_schema.json",
	"secrets_schema.json",
	"params_schema.json",
] as const;

const BANNER = `// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run \`pnpm gen:bindings\` to regenerate).
`;

/**
 * Read `@newton-xyz/policy-pack-shared`'s current published version at codegen
 * time so per-pack `package.json` files always emit a peer-dep range that
 * matches the shared package they were generated against. A hardcoded
 * constant would silently drift when shared bumps to 0.2.0.
 */
function resolveSharedPeerVersion(): string {
	const sharedPkgJsonPath = path.join(SHARED_PACKAGE_DIR, "package.json");
	if (!existsSync(sharedPkgJsonPath)) {
		fail(
			`missing ${sharedPkgJsonPath}; cannot derive @newton-xyz/policy-pack-shared peer-dep range. Bootstrap the shared package first.`,
		);
	}
	const pkg = readJson<{ version: string }>(sharedPkgJsonPath);
	if (!pkg.version || typeof pkg.version !== "string") {
		fail(
			`@newton-xyz/policy-pack-shared package.json has no version field; cannot derive peer-dep range.`,
		);
	}
	return `^${pkg.version}`;
}

interface DeploymentEntry {
	policy: string;
	policyData: string;
	wasmCid: string;
	policyCodeHash: string;
	deployedAt: string;
}

type GatewayEnv = "stagef" | "prod";

interface DeploymentsFile {
	schemaVersion: number;
	comment?: string;
	chains: Record<string, string>;
	envs?: Record<GatewayEnv, string>;
	packs: Record<string, Record<string, Partial<Record<GatewayEnv, DeploymentEntry>>>>;
}

interface PackMetadata {
	name: string;
	version: string;
	author?: string;
	link?: string;
	description: string;
}

function fail(message: string): never {
	console.error(`generate-bindings: ${message}`);
	process.exit(1);
}

function readJson<T>(filePath: string): T {
	return JSON.parse(readFileSync(filePath, "utf8")) as T;
}

function writeFile(filePath: string, content: string): void {
	mkdirSync(path.dirname(filePath), { recursive: true });
	writeFileSync(filePath, content, "utf8");
}

/**
 * Walk a JSON Schema and report whether it admits a top-level `_manifest`
 * field by any path. Returns a human-readable description of the offending
 * branch, or `null` if the schema rejects `_manifest` everywhere.
 *
 * Why every branch matters: a pack author could dodge a naive
 * `properties._manifest` check by routing the field through `oneOf` /
 * `anyOf` / `allOf` / `patternProperties`, or by leaving the schema open
 * (no `additionalProperties: false`). Each of those would let an on-chain
 * `policyParams` blob carry a top-level `_manifest` collision with the
 * composite-manifest discriminator. The walker covers every JSON Schema
 * variant we've seen pack authors use.
 */
export function findManifestKeyViolation(schema: unknown): string | null {
	return walk(schema, "<root>");

	function walk(node: unknown, where: string): string | null {
		if (!node || typeof node !== "object" || Array.isArray(node)) return null;
		const s = node as Record<string, unknown>;

		// Direct property declaration.
		const props = s.properties as Record<string, unknown> | undefined;
		if (props && "_manifest" in props) {
			return `${where}.properties._manifest`;
		}

		// Pattern-based property that could match `_manifest`. JSON Schema's
		// `patternProperties` keys are ECMA-262 regexes — test each against
		// the literal string `_manifest`.
		const patternProps = s.patternProperties as Record<string, unknown> | undefined;
		if (patternProps) {
			for (const pattern of Object.keys(patternProps)) {
				try {
					if (new RegExp(pattern).test("_manifest")) {
						return `${where}.patternProperties[${JSON.stringify(pattern)}] matches "_manifest"`;
					}
				} catch {
					// Invalid regex in the schema — not our problem; let zod codegen
					// surface it later. Continue scanning other keys.
				}
			}
		}

		// Note: we deliberately do NOT flag schemas that lack
		// `additionalProperties: false`. Zod's `.strict()` injection at
		// emitSchemaFile time enforces "no additional keys" at the SDK boundary,
		// so an open JSON Schema can't actually admit `_manifest` at runtime —
		// the curator would get a parse error from the generated zod schema
		// before the bytes reach `setPolicy(...)`. Flagging open schemas here
		// would force every existing pack to add `additionalProperties: false`
		// (real partner-facing churn) for a guard the runtime already provides.
		// The walker focuses on EXPLICIT `_manifest` declarations.

		// Recurse into combinators.
		for (const combinator of ["oneOf", "anyOf", "allOf"] as const) {
			const branches = s[combinator] as ReadonlyArray<unknown> | undefined;
			if (Array.isArray(branches)) {
				for (let i = 0; i < branches.length; i++) {
					const found = walk(branches[i], `${where}.${combinator}[${i}]`);
					if (found) return found;
				}
			}
		}

		// `not` is the only other JSON Schema combinator that nests a subschema —
		// `not: { properties: { _manifest: ... } }` would *forbid* `_manifest`,
		// which is fine. We don't recurse into `not`.

		return null;
	}
}

/** Discover all pack directories at the repo root that have a complete set
 *  of schema files + metadata. Skips dotfiles, `packages/`, `scripts/`, and
 *  `node_modules/`. */
function discoverPacks(): string[] {
	const packs: string[] = [];
	const skip = new Set([
		"packages",
		"scripts",
		"node_modules",
		".changeset",
		".git",
		".github",
		"dist",
	]);
	for (const entry of readdirSync(REPO_ROOT, { withFileTypes: true })) {
		if (!entry.isDirectory()) continue;
		if (entry.name.startsWith(".")) continue;
		if (skip.has(entry.name)) continue;
		const packDir = path.join(REPO_ROOT, entry.name);
		const hasAllSchemas = SCHEMA_FILES.every((f) => existsSync(path.join(packDir, f)));
		const hasMetadata = existsSync(path.join(packDir, "policy_metadata.json"));
		if (hasAllSchemas && hasMetadata) packs.push(entry.name);
	}
	return packs.sort();
}

function jsLiteral(value: unknown): string {
	return JSON.stringify(value, null, 2);
}

function emitSchemaFile(
	zodName: string,
	typeName: string,
	schema: unknown,
	sourceRelPath: string,
): string {
	const inner = jsonSchemaToZod(schema as Parameters<typeof jsonSchemaToZod>[0]);
	// Top-level `ParamsSchema` rejects unknown keys at the SDK boundary so a
	// curator typo throws in `encodePolicyParams` rather than getting silently
	// stripped and shipping AVS-rejecting bytes. Nested objects inside `inner`
	// are unaffected — only the outer chain gains `.strict()`.
	const expr = zodName === "ParamsSchema" ? `${inner}.strict()` : inner;
	return `${BANNER}// Source schema: ${sourceRelPath}
import { z } from "zod";

export const ${zodName} = ${expr};

export type ${typeName} = z.infer<typeof ${zodName}>;
`;
}

function emitMetadata(meta: PackMetadata): string {
	return `${BANNER}export const PACK_NAME = ${jsLiteral(meta.name)} as const;
export const PACK_VERSION = ${jsLiteral(meta.version)} as const;
export const PACK_DESCRIPTION = ${jsLiteral(meta.description)} as const;
export const PACK_LINK = ${jsLiteral(meta.link ?? "")} as const;
export const PACK_AUTHOR = ${jsLiteral(meta.author ?? "")} as const;
`;
}

function emitDeployments(
	perChain: Record<string, Partial<Record<GatewayEnv, DeploymentEntry>>>,
): string {
	return `${BANNER}import type { ChainId, Deployment, GatewayEnv } from "@newton-xyz/policy-pack-shared";

export const deployments = ${jsLiteral(
		perChain,
	)} as const satisfies Readonly<Partial<Record<ChainId, Readonly<Partial<Record<GatewayEnv, Deployment>>>>>>;
`;
}

function emitIndex(hasPackFile: boolean): string {
	const generatedReExports = `export * from "./wasm-args";
export * from "./secrets";
export * from "./params";
export * from "./deployments";
export * from "./metadata";
`;
	const packReExport = hasPackFile
		? `export * from "./pack";\n`
		: `// (no \`pack.ts\` yet — this pack ships generated bindings only. Add a hand-written \`pack.ts\`
// exporting a \`PolicyPack\` from \`@newton-xyz/policy-pack-shared\` to make it usable with createShield.)
`;
	return `${BANNER}${generatedReExports}${packReExport}`;
}

function emitPackageJson(packName: string, sharedPeerRange: string): string {
	return `${jsLiteral({
		name: `@newton-xyz/policy-pack-${packName}`,
		version: "0.1.0",
		description: `Typed TypeScript bindings for the Newton ${packName} policy pack.`,
		license: "Apache-2.0",
		author: "Newton Protocol <https://x.com/newton_xyz> (https://newton.xyz)",
		homepage: `https://github.com/newt-foundation/newton-policy-packs/tree/main/packages/policy-pack-${packName}`,
		repository: {
			type: "git",
			url: "git+https://github.com/newt-foundation/newton-policy-packs.git",
			directory: `packages/policy-pack-${packName}`,
		},
		bugs: {
			url: "https://github.com/newt-foundation/newton-policy-packs/issues",
		},
		keywords: ["newton", "newton-protocol", "policy-pack", "shield", packName],
		publishConfig: { access: "public" },
		sideEffects: false,
		type: "module",
		main: "./dist/index.cjs",
		module: "./dist/index.js",
		types: "./dist/index.d.ts",
		exports: {
			".": {
				types: "./dist/index.d.ts",
				import: "./dist/index.js",
				require: "./dist/index.cjs",
			},
		},
		files: ["dist", "README.md", "LICENSE"],
		scripts: {
			build: "tsup",
			dev: "tsup --watch",
			typecheck: "tsc --noEmit",
			test: "echo 'no tests yet'",
		},
		peerDependencies: {
			"@newton-xyz/policy-pack-shared": sharedPeerRange,
			viem: "^2.0.0",
			zod: "^3.0.0",
		},
		devDependencies: {
			"@newton-xyz/policy-pack-shared": "workspace:*",
			tsup: "^8.5.1",
			typescript: "^5.5.0",
			viem: "^2.0.0",
			zod: "^3.23.0",
		},
	})}\n`;
}

function emitTsconfig(): string {
	return `${jsLiteral({
		extends: "../../tsconfig.base.json",
		compilerOptions: { outDir: "dist", rootDir: "src" },
		include: ["src/**/*"],
		exclude: ["dist", "node_modules"],
	})}\n`;
}

function emitTsupConfig(): string {
	return `import { defineConfig } from "tsup";

export default defineConfig({
\tentry: ["src/index.ts"],
\tformat: ["esm", "cjs"],
\tdts: true,
\tsourcemap: true,
\tclean: true,
\tplatform: "neutral",
\ttarget: "es2022",
\texternal: ["viem", "zod", "@newton-xyz/policy-pack-shared"],
});
`;
}

function emitPackReadme(packName: string, meta: PackMetadata): string {
	return `# \`@newton-xyz/policy-pack-${packName}\`

${meta.description}

Typed TypeScript bindings for the Newton **${packName}** policy pack. Generated from the AVS-side artifacts at [\`/${packName}/\`](../../${packName}/) in this repo.

## Install

\`\`\`bash
pnpm add @newton-xyz/policy-pack-${packName}
\`\`\`

## What's exported

| Export | Source | Purpose |
|---|---|---|
| \`WasmArgsSchema\` (zod) + \`WasmArgs\` (type) | \`wasm_args_schema.json\` | Inputs the pack's WASM receives at evaluation time. |
| \`SecretsSchema\` (zod) + \`Secrets\` (type) | \`secrets_schema.json\` | API credentials uploaded before run/sim. |
| \`ParamsSchema\` (zod) + \`Params\` (type) | \`params_schema.json\` | Configuration thresholds, set at policy upload time. |
| \`deployments\` | top-level \`deployments.json\` | \`chainId → env → { policy, policyData, wasmCid, ... }\` (env keys: \`stagef\`, \`prod\`) |
| \`PACK_NAME\`, \`PACK_VERSION\`, \`PACK_DESCRIPTION\`, \`PACK_LINK\`, \`PACK_AUTHOR\` | \`policy_metadata.json\` | Static pack identity. |

## Regeneration

The \`src/*\` files are generated. Edit the upstream JSON schemas under [\`/${packName}/\`](../../${packName}/) and run \`pnpm gen:bindings\` from the repo root to regenerate.

The \`package.json\`, \`tsconfig.json\`, \`tsup.config.ts\`, and this README are scaffolded once and not overwritten on regen — you can hand-tune them.
`;
}

function camel(s: string): string {
	return s.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());
}

function main(): void {
	const deploymentsPath = path.join(REPO_ROOT, "deployments.json");
	if (!existsSync(deploymentsPath)) {
		fail(`missing deployments.json at ${deploymentsPath}`);
	}
	const deploymentsFile = readJson<DeploymentsFile>(deploymentsPath);

	const sharedPeerRange = resolveSharedPeerVersion();
	console.log(`generate-bindings: @newton-xyz/policy-pack-shared peer range = ${sharedPeerRange}`);

	const packs = discoverPacks();
	if (packs.length === 0) {
		fail(`no packs discovered at ${REPO_ROOT}`);
	}
	console.log(`generate-bindings: discovered ${packs.length} pack(s):`);
	for (const p of packs) console.log(`  - ${p}`);

	for (const packName of packs) {
		const packSrcDir = path.join(REPO_ROOT, packName);
		const packageDir = path.join(PACKAGES_DIR, `policy-pack-${packName}`);
		const srcDir = path.join(packageDir, "src");

		// Regenerate generated files only. Hand-written files in `src/` (e.g.
		// `pack.ts` exporting the canonical `PolicyPack` object, or
		// `prepare-query.ts` reading on-chain state) survive regen — only the
		// 6 files this script owns are wiped, not the whole `src/` directory.
		mkdirSync(srcDir, { recursive: true });
		const GENERATED_FILES = [
			"wasm-args.ts",
			"secrets.ts",
			"params.ts",
			"metadata.ts",
			"deployments.ts",
			"index.ts",
		] as const;
		for (const f of GENERATED_FILES) {
			const p = path.join(srcDir, f);
			if (existsSync(p)) rmSync(p);
		}

		const wasmArgsSchema = readJson<unknown>(path.join(packSrcDir, "wasm_args_schema.json"));
		const secretsSchema = readJson<unknown>(path.join(packSrcDir, "secrets_schema.json"));
		const paramsSchema = readJson<unknown>(path.join(packSrcDir, "params_schema.json"));
		// `_manifest` is reserved for the composite-policy manifest discriminator
		// (NEWT-1541, see `docs/composite-manifest-spec.md`). A pack declaring
		// `_manifest` at the top level of `params_schema.json` would collide with
		// the discriminator and break depositor verification. Codegen rejects it
		// here so the violation surfaces at PR time, not at production
		// `decodeManifest(...)` time.
		//
		// We walk every variant a JSON Schema can use to admit a top-level
		// `_manifest` field — direct `properties`, branch composites
		// (`oneOf`/`anyOf`/`allOf`), `patternProperties` (which can match
		// `_manifest` via regex), and a fully-open object (no
		// `additionalProperties: false`). Each branch is checked by a recursive
		// walker so nested combinators don't slip through.
		const violation = findManifestKeyViolation(paramsSchema);
		if (violation) {
			fail(
				`pack \`${packName}\` admits a top-level \`_manifest\` property in params_schema.json (${violation}) — that key is reserved for the composite-policy manifest discriminator (see docs/composite-manifest-spec.md). Tighten the schema or rename the property.`,
			);
		}
		const meta = readJson<PackMetadata>(path.join(packSrcDir, "policy_metadata.json"));

		writeFile(
			path.join(srcDir, "wasm-args.ts"),
			emitSchemaFile(
				"WasmArgsSchema",
				"WasmArgs",
				wasmArgsSchema,
				`${packName}/wasm_args_schema.json`,
			),
		);
		writeFile(
			path.join(srcDir, "secrets.ts"),
			emitSchemaFile("SecretsSchema", "Secrets", secretsSchema, `${packName}/secrets_schema.json`),
		);
		writeFile(
			path.join(srcDir, "params.ts"),
			emitSchemaFile("ParamsSchema", "Params", paramsSchema, `${packName}/params_schema.json`),
		);
		writeFile(path.join(srcDir, "metadata.ts"), emitMetadata(meta));

		const perChain = deploymentsFile.packs[packName] ?? {};
		writeFile(path.join(srcDir, "deployments.ts"), emitDeployments(perChain));

		// Re-export hand-written `pack.ts` if the maintainer has provided one.
		const packFilePath = path.join(srcDir, "pack.ts");
		const hasPackFile = existsSync(packFilePath);
		writeFile(path.join(srcDir, "index.ts"), emitIndex(hasPackFile));

		// Scaffold once. Don't overwrite if the pack maintainer has hand-tuned.
		const pkgJsonPath = path.join(packageDir, "package.json");
		if (!existsSync(pkgJsonPath)) {
			writeFile(pkgJsonPath, emitPackageJson(packName, sharedPeerRange));
		}
		const tsconfigPath = path.join(packageDir, "tsconfig.json");
		if (!existsSync(tsconfigPath)) {
			writeFile(tsconfigPath, emitTsconfig());
		}
		const tsupConfigPath = path.join(packageDir, "tsup.config.ts");
		if (!existsSync(tsupConfigPath)) {
			writeFile(tsupConfigPath, emitTsupConfig());
		}
		const readmePath = path.join(packageDir, "README.md");
		if (!existsSync(readmePath)) {
			writeFile(readmePath, emitPackReadme(packName, meta));
		}

		console.log(`  ✓ ${packName} → packages/policy-pack-${packName}/`);
	}

	// Formatting is the responsibility of `pnpm lint:fix`, not codegen. The
	// previous in-codegen biome call swallowed errors and could silently emit
	// unformatted files in environments without `pnpm` (e.g. fresh CI containers
	// before devDeps install). Decoupling avoids that footgun.

	// Suppress unused-import warnings while keeping the helper available for
	// future per-pack name-mangling needs (e.g. discriminated unions).
	void camel;

	console.log("\ngenerate-bindings: done.");
	console.log("  Next: `pnpm install && pnpm lint:fix && pnpm -r typecheck && pnpm -r build`.");
}

// Only auto-execute when run as a script (e.g. `pnpm gen:bindings`), NOT when
// imported by a test (e.g. `findManifestKeyViolation` self-test). `pathToFileURL`
// handles Windows backslashes and spaces in paths, which a manual
// `file://${argv[1]}` concatenation would mangle.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	main();
}
