// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
import type { ChainId, Deployment } from "@newton-xyz/policy-pack-shared";

export const deployments = {
	"11155111": {
		policy: "0xDF197d688426ac29182E46016bEe5f84BEB65A79",
		policyData: "0xF38bc16192dE633E93c60cc98D54514FaBA74332",
		wasmCid: "bafybeib6rithkstt6imntzyhl5mzvzl6ipj4engv7enipy6bje6kiadbjq",
		policyCodeHash: "0xc151d9fc12c4f3d77ba89c64ba28e8df6c780f4d36419cee6af5c9f13cc22254",
		deployedAt: "2026-06-12",
		notes: "round 2: tightened blockaid/guardrail/webacy allow rules; source-of-truth dist sync",
	},
} as const satisfies Readonly<Partial<Record<ChainId, Deployment>>>;
