// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "persona" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Gates permissioned vault deposits on Persona KYC: requires a recent approved inquiry bound to the sending wallet with passing government-ID, selfie, and watchlist verifications, plus country and age checks" as const;
export const PACK_LINK = "https://withpersona.com" as const;
export const PACK_AUTHOR = "" as const;
