// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: persona/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		max_age_days: z
			.number()
			.describe(
				"Maximum allowed age (in days) of the most recent approved Persona inquiry before it is considered stale",
			),
		allowed_countries: z
			.array(z.string())
			.describe(
				"ISO 3166-1 alpha-2 country codes whose users may deposit. Inquiries with no resolved country are not blocked by this rule.",
			),
		min_age_years: z
			.number()
			.describe(
				"Minimum user age in years (computed from the inquiry birthdate). Inquiries with no birthdate are not blocked by this rule.",
			),
		require_selfie: z
			.boolean()
			.describe("Whether to require a passing selfie verification on the inquiry"),
		require_watchlist_pass: z
			.boolean()
			.describe(
				"Whether to require a passing watchlist (sanctions/PEP) verification on the inquiry",
			),
	})
	.describe("KYC envelope thresholds for permissioned vault deposit gating");

export type Params = z.infer<typeof ParamsSchema>;
