// AUTO-GENERATED by scripts/generate-bindings.ts — DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: persona/secrets_schema.json
import { z } from "zod";

export const SecretsSchema = z.object({ PERSONA_API_KEY: z.string().min(1) }).strict();

export type Secrets = z.infer<typeof SecretsSchema>;
