// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "safe_signer_threshold" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Gates execution on a Safe's on-chain configuration: identity of the Safe, minimum signature threshold, and minimum/maximum owner count" as const;
export const PACK_LINK = "https://safe.global/" as const;
export const PACK_AUTHOR = "" as const;
