// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: safe_signer_threshold/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		safe_address: z
			.string()
			.regex(/^0x[0-9a-fA-F]{40}$/)
			.describe(
				"The Safe address this policy is bound to. The address the WASM actually read must match this (case-insensitive), otherwise deny.",
			),
		min_threshold: z
			.number()
			.describe("Minimum signature threshold the Safe must require. Below this, deny."),
		min_owners: z
			.number()
			.describe("Minimum number of owners (signers) the Safe must have. Below this, deny."),
		max_owners: z
			.number()
			.describe("Maximum number of owners (signers) the Safe may have. Above this, deny."),
	})
	.describe("Expected Safe identity and owner/threshold bounds for the Safe configuration gate")
	.strict();

export type Params = z.infer<typeof ParamsSchema>;

export const ParamsJsonSchema = {
	type: "object",
	description: "Expected Safe identity and owner/threshold bounds for the Safe configuration gate",
	properties: {
		safe_address: {
			type: "string",
			pattern: "^0x[0-9a-fA-F]{40}$",
			description:
				"The Safe address this policy is bound to. The address the WASM actually read must match this (case-insensitive), otherwise deny.",
		},
		min_threshold: {
			type: "number",
			description: "Minimum signature threshold the Safe must require. Below this, deny.",
		},
		min_owners: {
			type: "number",
			description: "Minimum number of owners (signers) the Safe must have. Below this, deny.",
		},
		max_owners: {
			type: "number",
			description: "Maximum number of owners (signers) the Safe may have. Above this, deny.",
		},
	},
	required: ["safe_address", "min_threshold", "min_owners", "max_owners"],
} as const;
