// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: safe_signer_threshold/secrets_schema.json
import { z } from "zod";

export const SecretsSchema = z
	.object({
		ETH_SEPOLIA_RPC_URL: z
			.string()
			.min(1)
			.describe("JSON-RPC endpoint for Ethereum Sepolia (chainId 11155111)."),
		BASE_SEPOLIA_RPC_URL: z
			.string()
			.min(1)
			.describe("JSON-RPC endpoint for Base Sepolia (chainId 84532)."),
	})
	.strict();

export type Secrets = z.infer<typeof SecretsSchema>;
