// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: safe_signer_threshold/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		safeAddress: z
			.string()
			.regex(/^0x[0-9a-fA-F]{40}$/)
			.describe(
				"Address of the Safe (Gnosis Safe) contract to read. getThreshold() and getOwners() are called on it.",
			),
		chainId: z
			.union([z.literal(11155111), z.literal(84532)])
			.describe(
				"Chain the Safe lives on. 11155111 = Ethereum Sepolia, 84532 = Base Sepolia. Selects which RPC-URL secret is used.",
			)
			.optional(),
		chain: z
			.enum(["eth-sepolia", "ethereum-sepolia", "sepolia", "base-sepolia"])
			.describe(
				"Optional human-readable alias for chainId. Only consulted when chainId is omitted.",
			)
			.optional(),
	})
	.describe(
		"Inputs passed to the Safe owner/threshold policy WASM at evaluation time. The JSON-RPC endpoints themselves are policy secrets, not wasm_args.",
	);

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
