// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
export const PACK_NAME = "xerberus_common_cause" as const;
export const PACK_VERSION = "0.0.1" as const;
export const PACK_DESCRIPTION =
	"Common-cause gate: denies when apparently diversified venues share a missing safeguard carrying too much combined exposure, a forbidden dependency, or an outsized shared collateral token" as const;
export const PACK_LINK = "https://xerberus.io" as const;
export const PACK_AUTHOR = "Xerberus" as const;
