// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: xerberus_common_cause/params_schema.json
import { z } from "zod";

export const ParamsSchema = z
	.object({
		max_shared_gap_exposure_usd: z
			.number()
			.gte(0)
			.describe(
				"Maximum combined USD exposure tolerated behind a single missing safeguard shared by several venues. The design reference uses 5000000.",
			),
		gap_failure_classes: z
			.array(z.string())
			.describe(
				"Failure classes the shared-gap limit applies to (case-insensitive). An empty list applies it to every class.",
			),
		forbidden_shared_dependencies: z
			.array(z.string())
			.describe(
				"Declared dependency targets (for example protocol:chainlink) that must not be shared across venues. Case-insensitive. An empty list disables the check.",
			),
		min_venues_for_shared_dependency: z
			.number()
			.gte(1)
			.describe(
				"How many venues must share a forbidden dependency before it denies. The design reference uses 2.",
			),
		max_shared_collateral_pct_of_book: z
			.number()
			.gte(0)
			.lte(100)
			.describe(
				"Maximum share (percent) of the compared exposure that may sit behind one shared collateral token. The design reference uses 25.",
			),
		material_subject_usd: z
			.number()
			.gte(0)
			.describe(
				"Exposure (USD) at or above which a venue Xerberus could not score counts as material.",
			),
		deny_on_unscored: z.boolean().describe("When true, deny if any material venue is unscored."),
		min_subjects_compared: z
			.number()
			.gte(0)
			.describe(
				"Minimum number of venues Xerberus must have compared. Cross-venue analysis needs at least 2.",
			),
		deny_on_stale: z
			.boolean()
			.describe("When true, deny whenever Xerberus flags its data window as stale (is_stale)."),
		max_data_age_seconds: z
			.number()
			.gte(0)
			.describe("Maximum tolerated age of the Xerberus data window, measured at evaluation time."),
		require_intent_party_in_wallets: z
			.boolean()
			.describe(
				"When true, deny unless the intent's sender or target is one of the analysed wallets.",
			),
	})
	.strict()
	.describe("Thresholds for the Xerberus common-cause gate")
	.strict();

export type Params = z.infer<typeof ParamsSchema>;

export const ParamsJsonSchema = {
	type: "object",
	description: "Thresholds for the Xerberus common-cause gate",
	properties: {
		max_shared_gap_exposure_usd: {
			type: "number",
			minimum: 0,
			description:
				"Maximum combined USD exposure tolerated behind a single missing safeguard shared by several venues. The design reference uses 5000000.",
		},
		gap_failure_classes: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Failure classes the shared-gap limit applies to (case-insensitive). An empty list applies it to every class.",
		},
		forbidden_shared_dependencies: {
			type: "array",
			items: {
				type: "string",
			},
			description:
				"Declared dependency targets (for example protocol:chainlink) that must not be shared across venues. Case-insensitive. An empty list disables the check.",
		},
		min_venues_for_shared_dependency: {
			type: "number",
			minimum: 1,
			description:
				"How many venues must share a forbidden dependency before it denies. The design reference uses 2.",
		},
		max_shared_collateral_pct_of_book: {
			type: "number",
			minimum: 0,
			maximum: 100,
			description:
				"Maximum share (percent) of the compared exposure that may sit behind one shared collateral token. The design reference uses 25.",
		},
		material_subject_usd: {
			type: "number",
			minimum: 0,
			description:
				"Exposure (USD) at or above which a venue Xerberus could not score counts as material.",
		},
		deny_on_unscored: {
			type: "boolean",
			description: "When true, deny if any material venue is unscored.",
		},
		min_subjects_compared: {
			type: "number",
			minimum: 0,
			description:
				"Minimum number of venues Xerberus must have compared. Cross-venue analysis needs at least 2.",
		},
		deny_on_stale: {
			type: "boolean",
			description: "When true, deny whenever Xerberus flags its data window as stale (is_stale).",
		},
		max_data_age_seconds: {
			type: "number",
			minimum: 0,
			description:
				"Maximum tolerated age of the Xerberus data window, measured at evaluation time.",
		},
		require_intent_party_in_wallets: {
			type: "boolean",
			description:
				"When true, deny unless the intent's sender or target is one of the analysed wallets.",
		},
	},
	required: [
		"max_shared_gap_exposure_usd",
		"gap_failure_classes",
		"forbidden_shared_dependencies",
		"min_venues_for_shared_dependency",
		"max_shared_collateral_pct_of_book",
		"material_subject_usd",
		"deny_on_unscored",
		"min_subjects_compared",
		"deny_on_stale",
		"max_data_age_seconds",
		"require_intent_party_in_wallets",
	],
	additionalProperties: false,
} as const;
