// AUTO-GENERATED by scripts/generate-bindings.ts - DO NOT EDIT.
// Source: AVS-side artifacts in this repo (run `pnpm gen:bindings` to regenerate).
// Source schema: xerberus_common_cause/wasm_args_schema.json
import { z } from "zod";

export const WasmArgsSchema = z
	.object({
		wallets: z
			.array(z.string())
			.min(1)
			.max(10)
			.describe(
				"Wallet addresses (0x-prefixed) holding the positions to compare. At least two Xerberus register-mapped venues across them are needed for a meaningful result.",
			),
		chain: z
			.literal("ethereum")
			.describe(
				"Optional Xerberus chain identifier. Only ethereum is supported today; defaults to ethereum.",
			)
			.optional(),
		window: z
			.string()
			.describe(
				"Optional Xerberus data-window timestamp (ISO-8601). Pass the same value to every xerberus_* pack in a composite.",
			)
			.optional(),
	})
	.describe("Inputs passed to the Xerberus common-cause policy WASM at evaluation time");

export type WasmArgs = z.infer<typeof WasmArgsSchema>;
